spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111

spring:
  thymeleaf:
    enabled: false
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
