DROP TABLE LISTINGS IF EXISTS;

CREATE TABLE LISTINGS (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            listing_type VARCHAR(64) NOT NULL,
            price INTEGER NOT NULL,
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL
            );
